improved getcrypto and computing crypto assets

diff --git a/statusbar/sb-crypto b/statusbar/sb-crypto
--- a/statusbar/sb-crypto
+++ b/statusbar/sb-crypto
@@ -5,18 +5,26 @@
 
 # coins to print
 coins="btc eth"
+chartcoins="btc eth ada dot bnb xmr link bat"
 
 # Directory where currency info is stored.
 dir="${XDG_DATA_HOME:-$HOME/.local/share}/crypto-prices"
+cachefile="${XDG_CACHE_HOME:-~/.cache}"/sb-crypto-cache
+assetsfile="${XDG_DATA_HOME:-$HOME/.local/share}/crypto-assets"
 
-cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e getcrypto:}'
+cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e getcrypto -g '"$chartcoins"':}'
+cmd2='%{A2:notify-send "$(cat '"$assetsfile"' | xargs getcrypto -t)":}'
 cmd3='%{A3:pkill -RTMIN+13 statusblocks:}'
 closecmd='%{A}'
+error=''
 
 printcrypto(){
-    echo "$cmd1$cmd3$prices$closecmd$closecmd"
+    echo "$error$cmd1$cmd2$cmd3$prices$closecmd$closecmd$closecmd"
 }
 
-prices=$(getcrypto -1b "$coins")
-
-printcrypto
+prices=$(getcrypto -b "$coins")
+if [ "$?" -gt 0 ]; then
+    echo "$(cat "$cachefile")"
+else
+    printcrypto | tee "$cachefile"
+fi
diff --git a/statusbar/sb-news b/statusbar/sb-news
--- a/statusbar/sb-news
+++ b/statusbar/sb-news
@@ -7,16 +7,18 @@ icon='參'
 cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e newsboat:}'
 cmd3='%{A3:pkill -RTMIN+6 statusblocks:}'
 closecmd='%{A}'
+error=''
+endtime=20
 
 cachefile="${XDG_CACHE_HOME:-~/.cache}"/sb-news-cache
 printnews(){
-    echo "$cmd1$cmd3$icon$news$closecmd$closecmd"
+    echo "$error$cmd1$cmd3$icon$news$closecmd$closecmd"
 }
 
 if [ "$(pgrep newsboat)" ]; then
     cat "$cachefile"
 else
-    newsboat -x reload
+    timeout "$endtime" newsboat -x reload || error=""
     news=$(newsboat -x print-unread | awk '{print $1}')
     printnews | tee "$cachefile"
 fi
