added prompt, fixed ueberzug-wrap to include args

diff --git a/fzfmenu b/fzfmenu
--- a/fzfmenu
+++ b/fzfmenu
@@ -1,3 +1,25 @@
 #!/bin/sh
 
-$TERMINAL -t fzfmenu -e sh -c "ueberzug-wrap fzf $* </proc/$$/fd/0 >/proc/$$/fd/1"
+args="--reverse --no-info"
+
+usage() {
+echo "Usage: fzfmenu [-h] [-p prompt]"
+}
+
+while getopts "p:h" option
+do
+	case "${option}" in
+		p)
+            args="$args --prompt=$OPTARG";;
+		h)
+            usage
+            exit 0;;
+		*)
+            echo "Error!" 1>&2
+            usage >&2
+            exit 1;;
+	esac
+done
+shift $((OPTIND-1))
+
+$TERMINAL -t fzfmenu -e sh -c "ueberzug-wrap fzf $args $* </proc/$$/fd/0 >/proc/$$/fd/1"
