setwall for lightdm, open, bar modules changes

diff --git a/setwall b/setwall
--- a/setwall
+++ b/setwall
@@ -1,6 +1,8 @@
 #!/bin/sh
 
 wallfile="$HOME/.local/share/wallpaper"
+sudo="doas"
+dm=
 
 # just refresh wallpaper
 if [ "$1" = "--restore" ]; then
@@ -8,16 +10,35 @@ if [ "$1" = "--restore" ]; then
     exit
 fi
 
+if [ "$1" = "--dm" ]; then
+    dm=1
+    shift
+fi
+
+get_random_img(){
+    find -L "$1" -type f | shuf -n 1
+}
+
 # get argument
 if [ -f "$1" ]; then
     img="$1"
 else
     if [ -d "$1" ]; then
-        dir="$1"
+        img=$(get_random_img "$1")
+    elif [ -z "$1" ]; then
+        if [ $dm ]; then
+            img=$(cat "$wallfile")
+        else
+            img=$(get_random_img "$HOME/media/wallpapers")
+        fi
     else
-        dir="$HOME"/media/wallpapers
+        echo "Could not parse argument $1" >&2
+        exit 1
     fi
-    img=$(find -L "$dir" -type f | shuf -n 1)
 fi
 
-echo "$(realpath "$img")" >"$wallfile" && setwall --restore
+if [ $dm ]; then
+    $sudo cp "$img" "/usr/share/pixmaps/background"
+else
+    echo "$(realpath "$img")" >"$wallfile" && setwall --restore
+fi
